server:
  port: 80
spring:
  application:
    name: zuul-server
zuul:
  routes:
    product-server:
      path: /product-server/** #需要被路由的路径
      #url: http://127.0.0.1:8001 #路由的地址
      service-id: product-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:9000/eureka,http://eureka2:9001/eureka
