server:
  port: 8080
spring:
  application:
    name: turbine-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://eureka2:9001/eureka/,http://eureka1:9000/eureka/
turbine:
  app-config: order-client
  clusterNameExpression: "'default'"
